### PR TITLE
Develop string

### PR DESCRIPTION
**Pull request by assertchris**
https://mootools.lighthouseapp.com/projects/24057/tickets/339-stringparsequerystring#ticket-339-5

Added new specs for the arguments/transformations to this method...

### CODE REVIEW

**Comment by arian** [comment]
Nice!

isn't it possible to update the commits of the pull request? Instead of 20 pull requests :)

**Comment by assertchris** [comment]
I don't know how :( Guess I should learn... :)

**Comment by kassens** [comment]
As long as you push to the same branch, the pull requests are updated. (It seems). I'm closing the 2 other pull requests.

**Comment by anutron** [comment]
This is now pulled

**Pull request closed without merging**
